version: '3.8'

services:
  app:
    build: .
    container_name: mini-task-scheduler-app
    ports:
      - "3002:3000"
    volumes:
      - .:/home/node/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/postgres
      - PORT=3000

  db:
    container_name: mini-task-scheduler-app-db
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "log_statement=all"]

volumes:
  postgres_data:
    driver: local
